# Generated by Django 3.2.6 on 2021-08-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_status', models.CharField(choices=[('-2', 'Game has not started'), ('-1', 'Playing...'), ('0', 'Draw'), ('1', 'First player'), ('2', 'Second Player')], max_length=100, verbose_name='Game Status')),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_player', to=settings.AUTH_USER_MODEL, verbose_name='First player')),
                ('second_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_player', to=settings.AUTH_USER_MODEL, verbose_name='Second player')),
            ],
        ),
    ]
