# Generated by Django 3.2.6 on 2021-08-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movements', models.TextField(blank=True, verbose_name='Movements')),
            ],
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='movements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.gameinstance'),
        ),
    ]
