# Generated by Django 3.2.6 on 2021-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210822_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='movements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GameInstance',
        ),
    ]
