# Generated by Django 3.2.6 on 2021-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210822_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='movements',
            field=models.TextField(blank=True, default=''),
        ),
    ]
