# Generated by Django 3.2.6 on 2021-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameinfo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
