# Generated by Django 3.2.6 on 2021-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gameinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='first_player_sign',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='second_player_sign',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
